# Sample docker-compose file to run a PostgreSQL server
version: "3.2"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myproject
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myproject
    ports:
      - "127.0.0.1:5499:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
